### PR TITLE
Fixed compiler warning.

### PR DESCRIPTION
**Pull request by stawiski**
Fixed issue #53

### CODE REVIEW

**Comment by EvilPudding** [comment]
This is not an appropriate solution.

**Comment by stawiski** [comment]
Well, you can implicitly cast as well: `(te_fun2*)s->function`.
Is that appropriate?

**Comment by EvilPudding** [comment]
Does `const te_fun2 t = (const te_fun2)s->function;` not fix it? I don't have msvc.

**Comment by stawiski** [comment]
> Can you post the exact warnings you were getting? Were you compiling as C or C++?

`tinyexpr\src\tinyexpr.c(628): warning C4090: 'initializing': different 'const' qualifiers`

I believe it's C compiler.

**Comment by stawiski** [comment]
> Does `const te_fun2 t = (const te_fun2)s->function;` not fix it? I don't have msvc.

That's what I suggested. I meant explicit cast, not implicit though.
Full line would be:
`const te_fun2* t = (te_fun2*)s->function;`

**Comment by stawiski** [comment]
Fixed two lines in `test.c` as well, one was a warning and one was an error:
`error C2440: 'initializing': cannot convert from 'void *' to 'double *'`

**Comment by stawiski** [comment]
> > Fixed two lines in `test.c` as well, one was a warning and one was an error:
> > `error C2440: 'initializing': cannot convert from 'void *' to 'double *'`
> 
> That really, really seems like a C++ error. Are you sure you're not compiling as C++?
> 
> Can you do a quick check for me? Compile this program and tell me if you get any errors:
> 
> ```
> int main() {
>     int class = 1;
> }
> ```

I admit, my unit tests are in C++, and I had to port your `test.c` into C++ and integrate it to our Catch2, but the main program should compile as C.
Nevertheless C or C++, don't you want to incorporate those changes?
How do they hurt the repo?

Cheers

**Comment by stawiski** [comment]
You can check for C++ easier:
```
#ifdef __cplusplus
#error "A C++ compiler has been selected for C."
#endif
```

I put this in `tinyexpr.c` and no error was triggered.

**Pull request closed without merging**
