### PR TITLE
Added arity greater than 2, and test cases.

### PR DESCRIPTION
**Pull request by EvilPudding**
I don't know what you think about the changes I made, please take a moment
to consider merging them. It supports functions with arity from 0 to 7, and
is somewhat easily scaled.
You might guess this changes lots of things, so I understand if you are
reluctant to merge it.

### CODE REVIEW

**Comment by codeplea** [comment]
It segfaults for me when running `test`. Seems to be on the very first test, with the expression `1`. I haven't had time to investigate further.

Other notes: you have tabs in a couple places and also some trailing white space. You might want to adjust your editor so you can see that stuff visually. Sorry, this is just a pet peeve of mine.

I'm not sure how I feel about the arbitrary arity in general. It complicates things a fair bit, in my opinion, and I don't have a use for it presently. I'll have to think about it.

But otherwise, good work! Looks like you put a lot of effort into this!

**Comment by codeplea** [comment]
BTW, it doesn't crash in gdb for me, but it is full of memory leaks and uninitialized reads.

**Comment by EvilPudding** [comment]
Wierd, to me it passes all the tests, are you sure you recompiled everything? And I remember specifically searching for all the tabs and replacing them, must have forgotten to do it in certain files. Gonna run valgrind, see if I find the root of the issues.

As to complicating things, I find quite the opposite, because we can make the functions more generic, and it won't occupy any extra memory if you don't use them. Another advantage is that now, functions with only one argument don't have the right expression allocated, saving memory.

**Comment by EvilPudding** [comment]
Valgrind states all memory was freed, this is very strange...
Are you merging things correctly?

**Comment by codeplea** [comment]
I didn't merge, I just did a `git clone` of your repository. I'll figure it out later and let you know.

You make a good case on your other points.

**Comment by EvilPudding** [comment]
I forgot to mention, it also does not allocate left and right for constants and variables.

**Comment by EvilPudding** [comment]
Ok... i'm dumb... forgot to assign member_count to the new te_expr...

**Comment by codeplea** [comment]
Yes, that was it.

**Comment by EvilPudding** [comment]
Fixed now, along with your new changes and tabs and trailing.
Speaking of which, I use vim, and my airline always warns me of trailing, I just didn't notice it this time... sorry.

**Comment by codeplea** [comment]
OK, I like it. I'll go ahead and do the merge. I'll probably make a few changes before putting it into master though (testing and documentation, at the very least).

**Comment by codeplea** [comment]
Anyway, thanks. I'm pretty happy with this.

**Comment by EvilPudding** [comment]
I'm glad it was approved!

**Comment by codeplea** [comment]
BTW, if you didn't notice, your changes greatly improved the performance (reported by the `bench` program). Very nice.

**Comment by EvilPudding** [comment]
Didn't run them, but it makes sense, but I'm guessing it's in memory and not speed, right?

**Comment by codeplea** [comment]
FYI, I did some refactoring:

I changed the `TE_FUN | 2` syntax to `TE_FUNCTION2` instead. I think it makes the code more obvious. Also, it turns the run-time error of `TE_FUN | 8` into the compile-time error `TE_FUNCTION8`, which I much prefer.

I removed the `member_count` variable. It wasn't needed since the `type` variable implies the number of function parameters already.

I got rid of the function `typedef`s in the header, since they aren't actually used in the public interface.

Also got rid of `TE_CONST` in the header, since it's not actually supported for the `te_variable` (since doubles are bigger than `void*` on most platforms).

I also renamed some other stuff, but most of that was just personal preference. Actually, it's all personal preference.

I still have a lot of work to do on the documentation and tests.

Anyway, just wanted to let you know why I made the changes in case you're still tweaking on this.

**Comment by EvilPudding** [comment]
That is an interesting free, but I was hoping to keep the stating of each function type to a minimum, so in case you decided to support more arguments, you wouldn't have to change in many places, but I think this is much more optimized.

I don't understand why you would make `TE_CONSTANT` separate from the other constants, if you were to combine them, and give the enum a name, like `te_type`, then you could make the `int type` of te_expr into `te_type type`, making it so you already get a warning when passing values that are not enumerated, and you wouldn't have to always check on runtime, if the type is valid every time you call the `ARITY`.

Completely unrelated, what would you think in having the following macro to make new_expr calls equal to before?

```c
#define new_expr(type, ...) _new_expr(type, (const te_expr*[]){__VA_ARGS__})
```

This would only be a preprocessor change, and wouldn't impact performance. The function would have to be tweaked though, because now, it would have to check the first parameter for a null pointer, because instead of receiving 0, it would receive `(const te_expr*[]){0}`.

**Comment by EvilPudding** [comment]
Also, I don't think it's good practice to typedef the te_funN types, when each is only used once, how about:
```c
            #define m(e) te_eval(n->parameters[e])
            #define te_fun(...) (double(*n->function)(__VA_ARGS__))
            case 0: return te_fun(void)();
            case 1: return te_fun(double)(m(0));
            case 2: return te_fun(double, double)(m(0), m(1));
            case 3: return te_fun(double, double, double)(m(0), m(1), m(2));
            case 4: return te_fun(double, double, double, double)(m(0), m(1), m(2), m(3));
            case 5: return te_fun(double, double, double, double, double)(m(0), m(1), m(2), m(3), m(4));
            case 6: return te_fun(double, double, double, double, double,double)(m(0), m(1), m(2), m(3), m(4), m(5));
            case 7: return te_fun(double, double, double, double, double, double, double)(m(0), m(1), m(2), m(3), m(4), m(5), m(6));
            #undef m
            #undef te_fun
```
Untested code btw.

**Comment by codeplea** [comment]
Yeah, I like your macro ideas. I'll put them both in.

It's probably a good idea about the enum too. I'm still reworking things here. I not sure about a clean way to have the `te_variable` structure support constants. Right now it stores `const void *address` which is too small on most platforms to store a `double`. If I change it to a union, then it makes the initialization syntax change. e.g.:
```C
te_variable x = {"name", {&name}, TE_WHATEVER}; /* Extra {} needed for union. */
```

I'm working on adding closures now. i.e. functions that take an extra context passed through at runtime.

**Comment by EvilPudding** [comment]
Or, if we want to be more fancy:
```c
#define m(e) te_eval(n->members[e])
#define call0() void
#define call1() call0(), m(0)
#define call2() call1(), m(1)
#define call3() call2(), m(2)
#define call4() call3(), m(3)
#define call5() call4(), m(4)
#define call6() call5(), m(5)
#define call7() call6(), m(6)
#define args0() void
#define args1() double
#define args2() args1(), double
#define args3() args2(), double
#define args4() args3(), double
#define args5() args4(), double
#define args6() args5(), double
#define args7() args6(), double
#define expand(t) t()
#define call(n) ((double(*)(expand(args##n)function)(expand(call##n))
case 0: call(0);
case 1: call(1);
/* ... */


```

**Comment by codeplea** [comment]
That's cool, but a bit too fancy for my tastes.

I did add in your macro ideas from earlier.

I also got closures working. Basically closures are the same as functions, but they take an extra `void*` that can be used for whatever the caller likes.

For example, imagine we're programming something like a spreadsheet and want to write a function to allow access to other cells:

```C
double get_cell_value(void *context, double x, double y) {
    struct spreadsheet *sheet = (struct spreadsheet*)context;
    return sheet->data[x][y];
}

te_variable lookup[] = {
    {"cell", get_cell_value, TE_CLOSURE2}
};

te_expr *ex = te_compile("5 * cell(1,2) / cell(1,3)", lookup, 1, &err);
new_cell = te_eval_closure(ex, &sheet)
```

I think this will be very extremely useful. I have a use-case for it in my other project.

Some parts of the code are a bit rough still, but it works. Also made it slower, but I can fix that by duplicating the code in `te_eval`, maybe with a macro. The `ARITY` macro is a mess now. I should probably go back to your bit mask idea. I just want to insulate that from the interface.

Anyway, done for today. I'll clean it up later.

**Comment by codeplea** [comment]
I did a little research, and all this function pointer casting is technically undefined behavior in the C standard. I mean it obviously works...

**Comment by EvilPudding** [comment]
Function casting works if the signature is the same, if it didn't work, function pointer unions could not work as well, because accessing unions is just casting.

I'll have to look into your code, because it doesn't make sense to slow the code because of just adding closures, maybe I can find a more efficient way.

**Comment by EvilPudding** [comment]
I'm finding `te_eval_closure` to be a bit weird, because if you pass a closure to the compiler, any eval should automatically reflect that. The user shouldn't have to call a different eval function.

Seen when you add variable pointers is before compiling, why don't you just add an extra member to te_variable called `void *data` or `void *context` which would be, in non null cases, passed as the first argument? Then you wouldn't need to create a new type of functions.

**Comment by EvilPudding** [comment]
Imagine you have multiple closures, how would you eval them all with the method you're using?

**Comment by codeplea** [comment]
Actually, the standard gives no guarantee that `void*` is the same size as a function pointer such as `void (*)(void)` or that it's the same size as a `double(*)(double, double)` or anything else. If they were all shoved into a union, that's okay because the compiler will allocate size for the largest member. But that would make the `te_variable` syntax much more annoying.

I happen to know the calling standards on x86 and understand that the pointers actually are all the same size. So I know it'll work (and it is common in other code), but it is technically undefined behavior by the standard.


I could add the `void *context` to the `te_variable` structure. That's probably a good idea. My use case has me changing the context for each `te_eval` call (and not wanting to recompile), but I can accomplish that by passing in a `void**` for the context. And as you said, your idea has the benefit of allowing multiple closures to have separate contexts and I avoid having two `te_eval` functions.

You've got me convinced. Thanks. I'll make the changes later.

**Comment by codeplea** [comment]
BTW, the way some other libraries (like lua) do the callback functions is to have everything use the same function signature. In our case, it would probably look like all the callback functions having the signature `double(*)(void*, double*)` and being passed in an array of `double`s for the arguments. So you'd have to do an adapter for `pow` like:

```C
double pow_adapter(void*, double* nums) {
    return pow(nums[0], nums[1]);
}
```

It might be slower with the indirection and having to push all the parameters into an array.

Just thinking out loud here.

**Comment by EvilPudding** [comment]
That would simplify the library, not the usage, I think the current method is much simpler for the user.
A way to avoid `void**` would be to have te_eval receive the contexts, but then it would be inconsistent not to be able to pass variables in the same way.
As to the function pointers, I can't see how having a union in the te_variable would complicate things, can you explain what you mean? We could make it more secure by either asserting the sizeof function pointers as being the same size of void pointer, or get the maximum between the types and allocate the memory accordingly.

**Comment by codeplea** [comment]
I did the change with closures. Now each closure can have its own context. I'll probably refactor it so it's stored in the `parameter` array to save space.

So right now `te_variable` is using a `void*` for variable and function pointers. If that was a union instead, then you'd initialize it like:
```C
te_variable example = {"test", {&test}, TE_FUNCTION2};
```

Notice the extra `{}` for the union initializer.

**Pull request merged**
