### PR TITLE
add ncr and npr

### PR DESCRIPTION
**Pull request by chendotjs**
Finish `ncr` and `npr` in a simple way. 
I think combinatorics calculation can be put into use right now and be merged into master.

### CODE REVIEW

**Comment by EvilPudding** [comment]
This code seems to take it upon itself to check for all kinds of overflows, which is good, but makes the rest of the code inconsistent, if we choose to add checks to all the current built in functions, we would be taking choice and speed away from the user.

May I suggest a compile flag that turns on these checks?

**Comment by chendotjs** [comment]
Thank you, EvilPudding. It seems a good advice. However, I believe that most users including me use tinyexpr to do simple calculations, which is not likely to cause overflow. But combinatorics may easily leads to overflow, that's why I add some checks and I don't think these checks will cause serious performance degradation. A correct result may be the most important.

If some macros are added to control checks when compiling, some calculation behaviors are undefined. For example, when calculating `ncr(300,100)`, what should the result be? inf or the incorrect result it calculates?

**Comment by EvilPudding** [comment]
>However, I believe that most users including me use tinyexpr to do simple calculations

If we are to assume this, we should specify in the documentation that it isn't meant to be fast. Place yourself on the mind of the average user though, if he does not care about performance, why would he be using `C`? I use it because it doesn't make checks by itself and does not hold my hand.

The reason this library isn't focused on being faster isn't to be more accurate, it's just so the code base is smaller and more accessible, adding an option to choose if these checks are made would not increase the size of the code in any relevant manner and would give choice to the user.

The incorrect result it calculates is dependent on undefined behavior since it depends on the CPU implementation (even if C99 says for certain cases that it isn't undefined, compilers tend to not care), if one disables checks, one has to expect the results will be whatever the CPU decides they are without checks.

**Comment by codeplea** [comment]
I haven't had time to go over this in detail, but here are my thoughts for now:

1) The checks are good. We shouldn't provided wrong answers. This is consistent with the other functions TinyExpr provides. For example, if you run `exp 9999` you should usually expect to get back `inf` and not some weird wrong overflowed answer. I also agree that combinatorics are special, because even really small inputs can make fantastically huge results.

2) A big issue with the code is that you're using `ncr_cache` and the function `ncr` in a way that's not reentrant safe.

3) This is my personal opinion, but I don't like the whole `ncr` function in general. I think TinyExpr would be better served by a much smaller as less efficient function without any caching.

I do think that your code is good and high quality, I just don't think that it makes sense to devote that much code and complexity to a very small part of TinyExpr. I'd suggest we just use the most straight-forward and simple way to implement those functions here, and that you should consider moving your existing code to a stand-alone library to provide high-quality and efficient combinatoric functions.

**Comment by EvilPudding** [comment]
I don't think it makes sense to detect overflows for some operations but not for others, if you do a very large exponent and don't overflow, then you multiply it by 2, you'll get a negative number, but if you do a slightly larger exponent you get `inf`, how is this reliable?

**Comment by codeplea** [comment]
> if you do a very large exponent and don't overflow, then you multiply it by 2, you'll get a negative number

I don't think this is true. TinyExpr uses floating point. You'll get `inf` on most any platform.

If you're actually getting TinyExpr to overflow, please give me an example (and open a new thread for it).

**Comment by EvilPudding** [comment]
>I don't think this is true. TinyExpr uses floating point. You'll get inf on most any platform.

I was asking from the start why would we have checks on some operations and not on others, the response I got was that those operations were more likely to cause overflows, which is the reason I keep talking about it being an inconsistency. If in fact, the reason for there being checks in these operations and not the others is that floating point operations don't need those checks and integer operations do, that makes it consistent, though it's the first time anyone mentions that in the whole thread. I haven't checked but I'll assume you're right.

**Comment by chendotjs** [comment]
>  If in fact, the reason for there being checks in these operations and not the others is that floating point operations don't need those checks and integer operations do, that makes it consistent
Yes, that is the reason. I use integer as a tradeoff mainly because of loss of precision in double,though it might still occur in other parts of the code.

**Comment by EvilPudding** [comment]
Integer operations are much faster, so it's the best way to do it knowing those operations don't need decimals.

**Pull request merged**
